apiVersion: v1
kind: Pod
metadata:
  labels:
    app: probe-readiness
  name: probe-readiness
spec:
  containers:
  - name: probe-readiness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 6000
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5